"""empty message

Revision ID: 265687c01f43
Revises: fe39d9e5d203
Create Date: 2023-11-19 14:04:18.760285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265687c01f43'
down_revision = 'fe39d9e5d203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
